---
abstract: 'Perl wrapper for the Qiita API'
author:
  - 'Yuuki Tsubouchi <yuki.tsubo@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Qiita
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Accessor::Lite: 0
  HTTP::Request: 0
  JSON: 0
  LWP::UserAgent: 0
  URI: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
